### ISSUE TITLE
[Webhooks] Info

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/kaskadi-webhooks-api#1]
@Holger-Will all the webhooks are now also registered to the new webhook API.

The different URLs are:
- `https://api.klimapartner.net/webhooks/status` for status update
- `https://api.klimapartner.net/webhooks/stock` for stock update
- `https://api.klimapartner.net/webhooks/tracking` for tracking number assignment
- `https://api.klimapartner.net/webhooks/refurbishment` for refurbishment actions

For each of them I'm still logging the payload in their lambda.

Only the `status` one is also handling order status update in ES

**Comment by Holger-Will** [comment]
you can log to elasticsearch. one index for all and one document type per webhook. this way we will have a queryable history of all changes that happened to our data.

**Comment by alexlemaire** [comment]
Done!

Now lambdas will log to respectively:
- `status-webhook-log`
- `stock-webhook-log`
- `tracking-webhook-log`
- `refurbishment-webhook-log`

In there I am logging the date at which the lambda ran + all the body payload we received from the webhook.

**Comment by Holger-Will** [comment]
oh... i think you misunderstood... i want one (1) index (`ysws-log`) and store all logs from all webhooks there. With docs like this:

```
{
  "type": "status",
  "what": "ever",
  "other": "data",
  "we": "get",
  "from": "this webhook"
}
```
...
```
{
  "type": "stock"
  ...
}
```
...
```
{
  "type": "tracking"
  ...
}
```

etc.

**Comment by alexlemaire** [comment]
Fixed!

- removed the old 4 indices (`status-webhook-log`, `stock-webhook-log`, `tracking-webhook-log`, `refurbishment-webhook-log`).
- added 1 new index for logging `ysws-logs`
- modified lambdas accordingly so they write docs into `ysws-logs`
- all docs have the following format:
```
{
  "type": "webhook_type",
  "date": "log_date",
  ...data_from_ysws_webhook
}
```

**Comment by alexlemaire** [comment]
Closing for now!
